### ISSUE TITLE
Windows運行出現 Class com/drakeet/purewriter/Main not found 錯誤

### ISSUE THREAD

**Issue by maotingyang** [LiarOnce/purewriter-desktop-liaronce-build#2]
下載後雙擊 exe 檔出現此錯誤，請問是少裝了甚麼東西嗎？

**Comment by LiarOnce** [comment]
如果你下载的是 nonJRE 版本，必须修改`Pure Writer.cfg`中的`app.runtime`的路径
https://purewriter.liaronce.com/#/windowsx86?id=配置-jre-路径（仅针对-nonjre，非此版本可无视这步）
