### ISSUE TITLE
deepin V20运行报错

### ISSUE THREAD

**Issue by dlguoming** [LiarOnce/purewriter-desktop-liaronce-build#3]
我在deepin V20的正式版下运行，提示如下：

Failed to find library. /home/topza/applications/PureWriter/runtime/lib/amd64/server/libjvm.so
PureWriter Failed to locate JNI_CreateJavaVM
PureWriter Failed to launch JVM

JAVA环境是openjdk 8，JavaFX是软件库的11，不知道问题出在哪。

包括使用原始的031自行编译也会报错：

Couldn't find Ant-JavaFX-library, please make sure you've installed some JDK which includes JavaFX (e.g. OracleJDK or OpenJDK and OpenJFX), and JAVA_HOME is set properly.

之前自己编译的021现在倒是还用的挺好。

不知道问题出在哪，编译小白，求大大指点一下。

**Comment by LiarOnce** [comment]
JavaFX版本不对，必须跟JDK版本相同，你需要装JavaFX 8
