### ISSUE TITLE
能否关闭 purewriter.liaronce.com 这个页面，因为它在谷歌中有错误的权重

### ISSUE THREAD

**Issue by drakeet** [LiarOnce/purewriter-desktop-liaronce-build#4]
您好，purewriter.liaronce.com 在 Google 搜索中出现在了比纯纯写作官网更高的位置，而且其中的内容已经严重过时了，很容易对用户产生误导，纯纯写作桌面版官网为：https://writer.drakeet.com/desktop

容易引起误导的权重：
![image](https://user-images.githubusercontent.com/5214214/149768932-8ab8b627-4c26-4f05-bbd9-df612ce21bf0.png)

过时的内容，纯纯写作桌面版最新版为 1.5.1，而这个项目 purewriter.liaronce.com 页面显示 0.3.1

所以，恳请关闭 purewriter.liaronce.com 这个页面，感谢！

**Comment by LiarOnce** [comment]
已经关闭。
